default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PG_HOST'] %>
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: <%= "serial-pinger_development" %>

test:
  <<: *default
  database: <%= "serial-pinger_test" %>

heroku:
  <<: *default
  database: <%= "serial-pinger_heroku" %>

staging:
  <<: *default
  database: <%= "serial-pinger_staging" %>

production:
  <<: *default
  database: <%= "serial-pinger_production" %>